package countries

var matchRuToCode = map[string]CountryCode{
	"Албания":              CountryCode(8),
	"Алжир":                CountryCode(12),
	"Американский Самоа":   CountryCode(16),
	"Андорра":              CountryCode(20),
	"Ангола":               CountryCode(24),
	"Ангилья":              CountryCode(660),
	"Антарктика":           CountryCode(10),
	"Антигуа и Барбуда":    CountryCode(28),
	"Аргентина":            CountryCode(32),
	"Армения":              CountryCode(51),
	"Аруба":                CountryCode(533),
	"Австралия":            CountryCode(36),
	"Австрия":              CountryCode(40),
	"Азербайджан":          CountryCode(31),
	"Багамские острова":    CountryCode(44),
	"Бахрейн":              CountryCode(48),
	"Бангладеш":            CountryCode(50),
	"Барбадос":             CountryCode(52),
	"Беларусь":             CountryCode(112),
	"Бельгия":              CountryCode(56),
	"Белиз":                CountryCode(84),
	"Бенин":                CountryCode(204),
	"Бермуды":              CountryCode(60),
	"Бутан":                CountryCode(64),
	"Боливия":              CountryCode(68),
	"Босния и Герцеговина": CountryCode(70),
	"Ботсвана":             CountryCode(72),
	"остров Буве":          CountryCode(74),
	"Бразилия":             CountryCode(76),
	"Британские территории Индийского океана": CountryCode(86),
	"Бруней":   CountryCode(96),
	"Болгария": CountryCode(100),
	"Бурунди":  CountryCode(108),
	"Камбоджа": CountryCode(116),
	"Камерун":  CountryCode(120),
	"Канада":   CountryCode(124),
	"острова Зеленого Мыса":              CountryCode(132),
	"Каймановы острова":                  CountryCode(136),
	"Центральная Африканская Республика": CountryCode(140),
	"Шри Ланка":                          CountryCode(144),
	"Чад":                                CountryCode(148),
	"Чили":                               CountryCode(152),
	"Китайская Народная Республика":    CountryCode(156),
	"остров Рождества":                 CountryCode(162),
	"Кокосовые острова":                CountryCode(166),
	"Колумбия":                         CountryCode(170),
	"Коморские острова":                CountryCode(174),
	"Конго":                            CountryCode(178),
	"Демократическая республика Конго": CountryCode(180),
	"острова Кука":                     CountryCode(184),
	"Коста Рика":                       CountryCode(188),
	"Кот-д'Ивуар":                      CountryCode(384),
	"Хорватия":                         CountryCode(191),
	"Куба":                             CountryCode(192),
	"Кипр":                             CountryCode(196),
	"Чехия":                            CountryCode(203),
	"Дания":                            CountryCode(208),
	"Джибути":                          CountryCode(262),
	"Доминика":                         CountryCode(212),
	"Доминиканская республика":         CountryCode(214),
	"Эквадор":                          CountryCode(218),
	"Египет":                           CountryCode(818),
	"Сальвадор":                        CountryCode(222),
	"Экваториальная Гвинея":            CountryCode(226),
	"Эритрея":                          CountryCode(232),
	"Эстония":                          CountryCode(233),
	"Эфиопия":                          CountryCode(231),
	"Фарерские острова":                CountryCode(234),
	"Фолклендские (Мальвинские) острова": CountryCode(238),
	"Фиджи":                        CountryCode(242),
	"Финляндия":                    CountryCode(246),
	"Франция":                      CountryCode(250),
	"Французская Гвиана":           CountryCode(254),
	"Французская Полинезия":        CountryCode(258),
	"Французские Южные Территории": CountryCode(260),
	"Габон":                        CountryCode(266),
	"Гамбия":                       CountryCode(270),
	"Грузия":                       CountryCode(268),
	"Германия":                     CountryCode(276),
	"Гана":                         CountryCode(288),
	"Гибралтар":                    CountryCode(292),
	"Греция":                       CountryCode(300),
	"Гренландия":                   CountryCode(304),
	"Гренада":                      CountryCode(308),
	"Гваделупа":                    CountryCode(312),
	"Гуам":                         CountryCode(316),
	"Гватемала":                    CountryCode(320),
	"Гвинея":                       CountryCode(324),
	"Гвинея-Бисау":                 CountryCode(624),
	"Гайана":                       CountryCode(328),
	"Гаити":                        CountryCode(332),
	"острова Герда и МакДональда": CountryCode(334),
	"Гондурас":        CountryCode(340),
	"Гонконг (Китай)": CountryCode(344),
	"Венгрия":         CountryCode(348),
	"Исландия":        CountryCode(352),
	"Индия":           CountryCode(356),
	"Индонезия":       CountryCode(360),
	"Иран":            CountryCode(364),
	"Ирак":            CountryCode(368),
	"Ирландия":        CountryCode(372),
	"Израиль":         CountryCode(376),
	"Италия":          CountryCode(380),
	"Ямайка":          CountryCode(388),
	"Япония":          CountryCode(392),
	"Иордания":        CountryCode(400),
	"Казахстан":       CountryCode(398),
	"Кения":           CountryCode(404),
	"Кирибати":        CountryCode(296),
	"Корея":           CountryCode(410),
	"Корейская Народная Демократическая республика": CountryCode(408),
	"Кувейт":               CountryCode(414),
	"Кыргызстан":           CountryCode(417),
	"Лаос":                 CountryCode(418),
	"Латвия":               CountryCode(428),
	"Ливан":                CountryCode(422),
	"Лесото":               CountryCode(426),
	"Либерия":              CountryCode(430),
	"Ливия":                CountryCode(434),
	"Лихтенштейн":          CountryCode(438),
	"Литва":                CountryCode(440),
	"Люксембург":           CountryCode(442),
	"Макао (Китай)":        CountryCode(446),
	"Македония":            CountryCode(807),
	"Мадагаскар":           CountryCode(450),
	"Малави":               CountryCode(454),
	"Малайзия":             CountryCode(458),
	"Мальдивские острова":  CountryCode(462),
	"Мали":                 CountryCode(466),
	"Мальта":               CountryCode(470),
	"Маршалловы острова":   CountryCode(584),
	"Мартиника":            CountryCode(474),
	"Мавритания":           CountryCode(478),
	"Маврикий":             CountryCode(480),
	"Майотта":              CountryCode(175),
	"Мексика":              CountryCode(484),
	"Микронезия":           CountryCode(583),
	"Молдова":              CountryCode(498),
	"Монако":               CountryCode(492),
	"Монголия":             CountryCode(496),
	"Монтсеррат":           CountryCode(500),
	"Марокко":              CountryCode(504),
	"Мозамбик":             CountryCode(508),
	"Мьянма":               CountryCode(104),
	"Намибия":              CountryCode(516),
	"Науру":                CountryCode(520),
	"Непал":                CountryCode(524),
	"Нидерланды":           CountryCode(528),
	"Антильские острова":   CountryCode(530),
	"Новая Каледония":      CountryCode(540),
	"Новая Зеландия":       CountryCode(554),
	"Никарагуа":            CountryCode(558),
	"Нигер":                CountryCode(562),
	"Нигерия":              CountryCode(566),
	"Ниуэ":                 CountryCode(570),
	"остров Норфолк":       CountryCode(574),
	"Марианские острова":   CountryCode(580),
	"Норвегия":             CountryCode(578),
	"Оман":                 CountryCode(512),
	"Пакистан":             CountryCode(586),
	"Палау":                CountryCode(585),
	"Палестина":            CountryCode(275),
	"Панама":               CountryCode(591),
	"Папуа - Новая Гвинея": CountryCode(598),
	"Парагвай":             CountryCode(600),
	"Перу":                 CountryCode(604),
	"Филиппины":            CountryCode(608),
	"остров Питкэрн":       CountryCode(612),
	"Польша":               CountryCode(616),
	"Португалия":           CountryCode(620),
	"Пуэрто-Рико":          CountryCode(630),
	"Катар":                CountryCode(634),
	"Реюньон":              CountryCode(638),
	"Румыния":              CountryCode(642),
	"Россия":               CountryCode(643),
	"Руанда":               CountryCode(646),
	"остров Святой Елены":  CountryCode(654),
	"Сент-Китс и Невис":    CountryCode(659),
	"Сент-Люсия":           CountryCode(662),
	"Сен-Пьер и Микелон":   CountryCode(666),
	"Сент-Винсент и Гренадины": CountryCode(670),
	"острова Самоа":            CountryCode(882),
	"Сан-Марино":               CountryCode(674),
	"Сан-Томе и Принсипи":      CountryCode(678),
	"Саудовская Аравия":        CountryCode(682),
	"Сенегал":                  CountryCode(686),
	"Сейшельские острова":      CountryCode(690),
	"Сьерра-Леоне":             CountryCode(694),
	"Сингапур":                 CountryCode(702),
	"Словакия":                 CountryCode(703),
	"Словения":                 CountryCode(705),
	"Соломоновы острова":       CountryCode(90),
	"Сомали":                   CountryCode(706),
	"ЮАР":                      CountryCode(710),
	"Южная Георгия и Южные Сандвичевы острова": CountryCode(239),
	"Испания": CountryCode(724),
	"Судан":   CountryCode(729),
	"Суринам": CountryCode(740),
	"острова Свалбард и Ян Майен": CountryCode(744),
	"Свазиленд": CountryCode(748),
	"Швеция":    CountryCode(752),
	"Швейцария": CountryCode(756),
	"Сирия":     CountryCode(760),
	"Тайвань (Республика Китай)": CountryCode(158),
	"Таджикистан":                CountryCode(762),
	"Танзания":                   CountryCode(834),
	"Тайланд":                    CountryCode(764),
	"Восточный Тимор":            CountryCode(626),
	"Того":                       CountryCode(768),
	"Токелау":                    CountryCode(772),
	"Тонга":                      CountryCode(776),
	"Тринидад и Тобаго":          CountryCode(780),
	"Тунис":                      CountryCode(788),
	"Турция":                     CountryCode(792),
	"Туркменистан":               CountryCode(795),
	"острова Туркс и Кайкос":     CountryCode(796),
	"Тувалу":                     CountryCode(798),
	"Уганда":                     CountryCode(800),
	"Украина":                    CountryCode(804),
	"Арабские Эмираты":           CountryCode(784),
	"Великобритания":             CountryCode(826),
	"Соединенные Штаты Америки":  CountryCode(840),
	"Отдаленные Острова США":     CountryCode(581),
	"Буркина Фасо":               CountryCode(854),
	"Уругвай":                    CountryCode(858),
	"Узбекистан":                 CountryCode(860),
	"Вануату":                    CountryCode(548),
	"Ватикан":                    CountryCode(336),
	"Венесуэла":                  CountryCode(862),
	"Вьетнам":                    CountryCode(704),
	"Виргинские острова (Британские)": CountryCode(92),
	"Виргинские острова (США)":        CountryCode(850),
	"острова Валлис и Футуна":         CountryCode(876),
	"Западная Сахара":                 CountryCode(732),
	"Йемен":                           CountryCode(887),
	"Югославия":                       CountryCode(891),
	"Замбия":                          CountryCode(894),
	"Зимбабве":                        CountryCode(716),
	"Афганистан":                      CountryCode(4),
	"Сербия":                          CountryCode(688),
	"Аландские острова":               CountryCode(248),
	"Бонэйр, Синт-Эстатиус и Саба":    CountryCode(535),
	"Гернси":                          CountryCode(831),
	"Джерси":                          CountryCode(832),
	"Кюрасао":                         CountryCode(531),
	"Остров Мэн":                      CountryCode(833),
	"Сен-Бартелеми":                   CountryCode(652),
	"Сен-Мартен":                      CountryCode(663),
	"Синт-Мартен":                     CountryCode(534),
	"Черногория":                      CountryCode(499),
	"Южный Судан":                     CountryCode(728),
	"Косово":                          CountryCode(900),
	"Отсутствует":                     None,
	"International":                   International,
	"Бесплатный номер":                CountryCode(999800),
	"Инмарсат":                        CountryCode(999870),
	"Морская подвижная служба":        CountryCode(999875),
	"Универсальная персональная связь":                          CountryCode(999878),
	"Некоммерческое использование":                              CountryCode(999879),
	"Глобальная мобильная спутниковая система":                  CountryCode(999881),
	"Глобальные телефонные номера":                              CountryCode(999882),
	"Ликвидация последствий катастроф":                          CountryCode(999888),
	"Международная услуга оплаты вызова по повышенному тарифу":  CountryCode(999979),
	"Служба международной телекоммуникационной корреспонденции": CountryCode(999991),
}
